---
- hosts: all
  gather_facts: false
  #vars:
    #var1: praveen
    #var2: is
    #var3: king
  vars_files:
    - variables.yaml
  vars:
    var1: "{{ extra_vars.var1 | default(github_vars.var1) }}"
    var2: "{{ extra_vars.var2 | default(github_vars.var2) }}"
    var3: "{{ extra_vars.var3 | default(github_vars.var3) }}"
  tasks:
    - name: Do something with my variables
      debug:
        var:
          - var1
          - var2
          - var3
  
  tasks:
    - name: Install latest httpd package
      package:
        name: httpd
        state: latest
        
    - name: Create index.html file
      copy:
        content: '{{var1}} {{var2}} {{var3}}'     # The content to copy to the file
        dest: ~/index.html   # The destination file path    

    - name: Copy updated index.html content
      become: true
      copy:
        remote_src: yes
        src: ~/index.html
        dest: /var/www/html/index.html
        mode: 0644

    - name: Ensure httpd service is started
      service:
        name: httpd
        state: started
