---
- hosts: all
  gather_facts: false
  vars:
    var1: praveen
    var2: is
    var3: king
  tasks:
    - name: Install latest httpd package
      package:
        name: httpd
        state: latest
        
    - name: Create index.html file
      copy:
        content: 'hello {{var1}} {{var2}} {{var3}}'     # The content to copy to the file
        dest: ~/index.html   # The destination file path    

    - name: Copy updated index.html content
      become: true
      copy:
        remote_src: yes
        src: ~/index.html
        dest: /var/www/html/index.html
        mode: 0644

    - name: Ensure httpd service is started
      service:
        name: httpd
        state: started
