---
- hosts: all
  gather_facts: false
  #vars:
   #  stage: "{{ stage | default('dev') }}"
  #tasks:
    #- name: Load variable file based on stage
      #include_vars: "env-variables/{{ stage }}-variables.yml"
  vars:
    stage: 
  tasks:
    - name: Load variable file based on stage
      include_vars: "env-variables/{{ stage }}-variables.yml"
      when: stage in ['dev', 'prod']
      
    - name: Load default variable file if no dev or prod file exists
      include_vars: "env-variables/default-variables.yml"
      when: stage not in ['dev', 'prod']

    - name: Print loaded variables
      debug:
        var: env

        
    - name: Install latest httpd package
      package:
        name: httpd
        state: latest
        
    - name: Create index.html file
      copy:
        content: "hello {{ var1 }} {{ var2 }} {{ var3 }}"     # The content to copy to the file
        dest: ~/index.html   # The destination file path

    - name: Copy updated index.html content
      become: true
      copy:
        remote_src: yes
        src: ~/index.html
        dest: /var/www/html/index.html
        mode: 0644

    - name: Ensure httpd service is started
      service:
        name: httpd
        state: started
