---
- hosts: all
  tasks:
    - name: Install latest httpd package
      package:
        name: httpd
        state: latest

    - name: Copy updated index.html content
      become: true
      copy:
        remote_src: yes
        src: /var/lib/awx/projects
        dest: /var/www/html/index.html"
        mode: '0644'

    - name: Ensure httpd service is started
      service:
        name: httpd
        state: started
