---
- hosts: all
  gather_facts: false
  #vars:
    #var1: praveen
    #var2: is
    #var3: king
  #vars_files:
   # - variables.yaml
  vars:
    env: "prod"  # Change this to "dev" or "prod" to load the appropriate variables
  tasks:
    - name: Load variables based on environment
      include_vars:
        file: "env/{{ env }}-variables.yml"
        name: env_vars
      when: env in ['dev', 'prod']
    - name: Print loaded variables
      debug:
        var: env_vars
  tasks:
    - name: Install latest httpd package
      package:
        name: httpd
        state: latest
        
    - name: Create index.html file
      copy:
        content: 'hello {{var1}} {{var2}} {{var3}}'     # The content to copy to the file
        dest: ~/index.html   # The destination file path    

    - name: Copy updated index.html content
      become: true
      copy:
        remote_src: yes
        src: ~/index.html
        dest: /var/www/html/index.html
        mode: 0644

    - name: Ensure httpd service is started
      service:
        name: httpd
        state: started
